### ISSUE TITLE
Suggestions for ConTEXT-explorer dashboard

### ISSUE THREAD

**Issue by baileythegreen** [alicia-ziying-yang/conTEXT-explorer#3]
Here are some thoughts I've had when playing around with the dashboard. These are mostly UI/UX-related, and none of them are about things that are 'broken' or absolutely have to be fixed; they're just things I think would constitute improvements. I've put them all in one issue with headings so it's easier to read through, but am happy to resubmit some or all of them as individual issues so the suggestions can be considered on an individual basis.

## General
- Having all of the scroll bars remain visible all of the time would be an improvement. Right now, some of them seem permanently visible, but others disappear when the mouse isn't hovering over them (Overview–Top 30 Words; Groups–top section; Graphs–bottom section). The user could miss that these sections scroll, and not find the data they are looking for.
- The ability to download a report of some kind that is easily shareable and comparable between analyses would be a nice addition. Because the dashboard is interactive, maybe letting the user set things they way they want, then download the current configuration of the data would make sense.
- A 'save all' button for the graphs in the Groups and Graphs tab would similarly be very nice.
- Some way to share settings—like, when I save an analysis, does this produce a configuration file I could send to someone?

## Sentences
- This tab seems to reset automatically if you navigate away (to another tab), and then back. This may be frustrating for users.

## Graphs
- It might be worth considering whether users are going to use the Graphs tab to try to directly compare individual words/phrases from different sets of words (i.e., the contents of two of the bottom graphs). With the proportions, it may make sense to fix the y-axis to always show the full range, as this is fixed, so that direct comparison is possible.
- The graphs on this tab all have a 'Box select' and a 'Lasso select' option (the Top 30 Words one does, as well), that let users select a portion of the graph, but it doesn't appear that this has any bearing on anything else. I can't, for example, select part of a graph and download only that part, or zoom in on that part. It's unclear why the options exist.

## Save
- State on the boxes for each group whether they are an 'Any' or an 'All' grouping. The colour system is nice to reinforce this, but requires the user to remember the settings, and is a bit confusing because the colours are described as 'pink' and 'red' in the pdf, but against the dark background it's not at all clear that the light colour is pink, and the red colour is kind of a dark orangey-pink to my eye.

JOSS Reference: openjournals/joss-reviews#3347

**Comment by alicia-ziying-yang** [comment]
Hi @baileythegreen ,
Thank you so much for giving these ideas. Given the limited time and funding, we cannot implemented all of them now. So I listed some of them into the issues of the wish list. And for some others, please see the reply below.

**General**

- The ability to download a report of some kind that is easily shareable and comparable between analyses would be a nice addition. Because the dashboard is interactive, maybe letting the user set things they way they want, then download the current configuration of the data would make sense.   #9 

- A 'save all' button for the graphs in the Groups and Graphs tab would similarly be very nice. #10 

- Some way to share settings—like, when I save an analysis, does this produce a configuration file I could send to someone? (Re: the saved analysis will be "saved" into the application folders, and other users can reload all the "settings")

**Sentences**
This tab seems to reset automatically if you navigate away (to another tab), and then back. This may be frustrating for users.(Re: yes the sentences search the corpus again every time, because the query could be changed by users when users view other tabs.)

**Graphs**
- It might be worth considering whether users are going to use the Graphs tab to try to directly compare individual words/phrases from different sets of words (i.e., the contents of two of the bottom graphs). With the proportions, it may make sense to fix the y-axis to always show the full range, as this is fixed, so that direct comparison is possible. #11 

- The graphs on this tab all have a 'Box select' and a 'Lasso select' option (the Top 30 Words one does, as well), that let users select a portion of the graph, but it doesn't appear that this has any bearing on anything else. I can't, for example, select part of a graph and download only that part, or zoom in on that part. It's unclear why the options exist. (Re: this is a issue for Plotly, we cannot change. Maybe users can simply make a screenshot for the zoomed graph.)

**Save**

- State on the boxes for each group whether they are an 'Any' or an 'All' grouping. The colour system is nice to reinforce this, but requires the user to remember the settings, and is a bit confusing because the colours are described as 'pink' and 'red' in the pdf, but against the dark background it's not at all clear that the light colour is pink, and the red colour is kind of a dark orangey-pink to my eye. #12

**Comment by baileythegreen** [comment]
Thanks for considering these!

I wanted to clarify that this suggestion:

> Some way to share settings—like, when I save an analysis, does this produce a configuration file I could send to someone?

is about sharing things with people who **do not** have access to the same computer. For example, I, like many people these days, work remotely, and have never even met the people in my team *in person*. Even if we were in the same place, we all have our own computers we would run analyses on. So, this:

> (Re: the saved analysis will be "saved" into the application folders, and other users can reload all the "settings")

doesn't address the point of the suggestion, and is why I tried to clarify by saying I wanted to 'send' it.

**Comment by alicia-ziying-yang** [comment]
> Thanks for considering these!
> 
> I wanted to clarify that this suggestion:
> 
> > Some way to share settings—like, when I save an analysis, does this produce a configuration file I could send to someone?
> 
> is about sharing things with people who **do not** have access to the same computer. For example, I, like many people these days, work remotely, and have never even met the people in my team _in person_. Even if we were in the same place, we all have our own computers we would run analyses on. So, this:
> 
> > (Re: the saved analysis will be "saved" into the application folders, and other users can reload all the "settings")
> 
> doesn't address the point of the suggestion, and is why I tried to clarify by saying I wanted to 'send' it.

Actually yes, it is possible, but only when they have the same corpus with the same parameters when uploading. If so, then just copy and paste the analysis config file to the same folder in another computer. But we suggest, just hosting this app on a server that every member can access...

**Comment by baileythegreen** [comment]
Okay, then maybe add something to the Readme that explains where to find the config files. I have looked for something like that, but have not yet managed to find where they are stored; this may just be that I don't know how they are named, or what file extension they would use, but if that's the case, it won't be any different for the users.
